window.CURRICULUM_DATA = {
  subjects: {
    "语文": { color: "oklch(0.64 0.185 20)", domains: ["识字与写字", "阅读", "表达与交流", "传统文化"] },
    "数学": { color: "oklch(0.6 0.175 260)", domains: ["数与代数", "图形与几何", "统计与概率", "综合实践"] },
    "英语": { color: "oklch(0.59 0.17 305)", domains: ["听说", "阅读", "词汇与语法", "表达"] },
    "科学": { color: "oklch(0.64 0.145 165)", domains: ["生命科学", "物质科学", "地球与宇宙", "技术与工程"] }
  },
  topics: [
    {id:"cn-yw-101",subject:"语文",domain:"识字与写字",grade:1,name:"认识汉字的基本笔画",description:"认识横、竖、撇、捺、点等基本笔画，理解笔画是构成汉字的基本单位。",evidence:["能说出常见基本笔画名称","能按正确方向书写基本笔画"]},
    {id:"cn-yw-102",subject:"语文",domain:"识字与写字",grade:1,name:"汉语拼音声母与韵母",description:"认识常用声母、韵母，能够正确认读并尝试拼读音节。",evidence:["准确认读声母和单韵母","能拼读简单的两拼音节"]},
    {id:"cn-yw-103",subject:"语文",domain:"阅读",grade:1,name:"借助拼音读短句",description:"借助汉语拼音准确朗读由常用字组成的简短句子。",evidence:["能连续拼读一个短句","朗读时做到字音基本正确"]},
    {id:"cn-yw-201",subject:"语文",domain:"识字与写字",grade:2,name:"部首查字法",description:"认识常用部首，并能使用部首查字法在字典中查找不认识的汉字。",evidence:["判断汉字的常见部首","按部首和剩余笔画查到汉字"]},
    {id:"cn-yw-202",subject:"语文",domain:"表达与交流",grade:2,name:"看图写完整句子",description:"观察画面中的人物、动作和环境，用通顺、完整的句子表达主要内容。",evidence:["写出包含人物和动作的句子","正确使用句号或问号"]},
    {id:"cn-yw-301",subject:"语文",domain:"阅读",grade:3,name:"概括自然段大意",description:"抓住自然段中的关键句和关键词，用简洁语言概括主要意思。",evidence:["找出段落关键内容","用一至两句话准确概括"]},
    {id:"cn-yw-302",subject:"语文",domain:"传统文化",grade:3,name:"理解古诗中的画面",description:"结合注释和生活经验，想象古诗描写的景物、人物和情境。",evidence:["说出诗句描写的主要景物","用自己的话描述诗中画面"]},
    {id:"cn-yw-401",subject:"语文",domain:"阅读",grade:4,name:"体会文章表达的情感",description:"从人物、事件、景物和关键词句中体会作者表达的思想感情。",evidence:["找出体现情感的关键词句","结合内容说明自己的判断"]},
    {id:"cn-yw-402",subject:"语文",domain:"表达与交流",grade:4,name:"把事情写清楚",description:"按照一定顺序写清事情的起因、经过和结果，并关注重要细节。",evidence:["叙事顺序清楚","能围绕重点写出具体细节"]},
    {id:"cn-yw-501",subject:"语文",domain:"阅读",grade:5,name:"阅读中提出有价值的问题",description:"从内容、写法和获得的启示等角度提出能够推动深入理解的问题。",evidence:["问题与文本重点相关","能通过阅读和讨论寻找答案"]},
    {id:"cn-yw-502",subject:"语文",domain:"表达与交流",grade:5,name:"用具体事例写人物特点",description:"选择典型事例，通过语言、动作、神态等描写表现人物特点。",evidence:["事例能够支持人物特点","至少使用一种细节描写"]},
    {id:"cn-yw-601",subject:"语文",domain:"阅读",grade:6,name:"理解文章的中心意思",description:"综合题目、主要事件、关键语句和结尾，归纳文章表达的中心意思。",evidence:["区分主要内容与中心意思","能引用文本依据说明中心"]},

    {id:"cn-sx-101",subject:"数学",domain:"数与代数 · 数的认识",grade:1,order:1,name:"数数与一一对应",description:"按顺序一个一个数，也能两个、五个、十个一组地数；做到不重复、不遗漏，并让物体数量与数字对应。",evidence:["按指定方式数出物体数量","把1至10的数字与相应数量配对"],examples:["数苹果：1个苹果、2个苹果、3个苹果...一直数到10","数手指：一只手5个手指，两只手10个手指","五个五个数：5、10、15、20..."],tips:["数的时候可以用手指指着物体，一个一个数","可以边数边做记号，避免重复或漏掉","五个五个数时，可以用一只手的手指做标记"],commonMistakes:["数的时候跳着数，比如1、2、4、5...漏掉了3","数到9不知道接下来是10","把同一个物体数两次"],source:"一年级代数知识点导图"},
    {id:"cn-sx-102",subject:"数学",domain:"数与代数 · 数的认识",grade:1,order:2,name:"认识0至10",description:"认识0至10各数，理解0既可以表示一个也没有，也可以表示起点；知道9添1是10。",evidence:["正确读写0至10","说明生活中0的不同含义"],examples:["盘子里没有苹果，可以用0表示","尺子的起点是0","温度计上的0是零上和零下的分界"],tips:["0像一个鸡蛋，圆圆的","记住数字的形状：1像铅笔、2像鸭子、3像耳朵...","9添1就是10，10由1和0组成"],commonMistakes:["把0写成6或9","不知道0可以表示起点","忘记9后面是10"],source:"一年级代数知识点导图"},
    {id:"cn-sx-103",subject:"数学",domain:"数与代数 · 数的认识",grade:1,order:3,name:"几、第几与比较多少",description:"区分表示总数量的“几”和表示排列位置的“第几”，通过一一对应判断同样多、谁多和谁少。",evidence:["区分基数与序数","用一一对应比较两组物体"],source:"一年级代数知识点导图"},
    {id:"cn-sx-104",subject:"数学",domain:"数与代数 · 加减法",grade:1,order:4,name:"加法和减法的意义",description:"理解加法表示把两部分合在一起求总数，减法表示从总数中去掉一部分求剩余；认识加号、减号和等号。",evidence:["根据合并或去掉情境选择加减法","正确读写简单加减算式"],examples:["小明有3个苹果，妈妈又给了2个，一共有几个？3+2=5","树上有5只小鸟，飞走了2只，还剩几只？5-2=3","加法：把两部分合起来；减法：从总数里去掉一部分"],tips:["加号“+”像一个十字架","减号“-”像一条横线","记住：合起来用加法，去掉用减法"],commonMistakes:["把加法和减法弄混","忘记写等号“=”","不会读算式：3+2读作“3加2”"],source:"一年级代数知识点导图"},
    {id:"cn-sx-105",subject:"数学",domain:"数与代数 · 加减法",grade:1,order:5,name:"5以内加减法",description:"借助实物、点数和画图掌握5以内全部加减法，理解加减法互逆以及与0有关的运算。",evidence:["熟练计算5以内加减法","用图或实物解释一个算式"],source:"一年级代数知识点导图"},
    {id:"cn-sx-106",subject:"数学",domain:"数与代数 · 加减法",grade:1,order:6,name:"6至10的分与合和加减法",description:"通过分一分、画图和情境理解6、7、8、9、10的多种分合，并形成相应的加减法事实。",evidence:["说出6至10的主要分合","根据一个分合写出相关加减算式"],source:"一年级代数知识点导图"},
    {id:"cn-sx-107",subject:"数学",domain:"数与代数 · 加减法",grade:1,order:7,name:"连加、连减与加减混合",description:"根据连续变化的画面列出连加、连减或加减混合算式，并按从左到右的顺序计算。",evidence:["把连续情境写成算式","按顺序正确计算两步算式"],source:"一年级代数知识点导图"},
    {id:"cn-sx-108",subject:"数学",domain:"数与代数 · 问题解决",grade:1,order:8,name:"求差、缺多少与移多补少",description:"用大数减小数求相差数，解决谁比谁多或少、还缺多少，以及把多出的一半移给较少一方等问题。",evidence:["用减法求两数相差多少","借助画图说明移多补少"],source:"一年级代数知识点导图"},
    {id:"cn-sx-109",subject:"数学",domain:"数与代数 · 数的认识",grade:1,order:9,name:"20以内数的组成与比较",description:"理解10个一是1个十，十几由1个十和几个一组成；正确读写并比较20以内各数。",evidence:["说出十几的组成","比较20以内数的大小"],source:"一年级代数知识点导图"},
    {id:"cn-sx-110",subject:"数学",domain:"数与代数 · 加减法",grade:1,order:10,name:"十几加几（不进位）",description:"把十几看作1个十和几个一，只把个位相加，十位保持不变。",evidence:["用数的组成解释十几加几","正确计算不进位加法"],source:"一年级代数知识点导图"},
    {id:"cn-sx-111",subject:"数学",domain:"数与代数 · 加减法",grade:1,order:11,name:"20以内进位加法",description:"掌握凑十法、接着数、想加法模型和计数器满十进一等方法计算20以内进位加法。",evidence:["用凑十法解释进位过程","正确计算20以内进位加法"],source:"一年级代数知识点导图"},
    {id:"cn-sx-112",subject:"数学",domain:"数与代数 · 加减法",grade:1,order:12,name:"20以内退位减法",description:"掌握破十法、平十法、想加算减和倒数等方法计算20以内退位减法。",evidence:["选择一种方法解释退位过程","正确计算20以内退位减法"],source:"一年级代数知识点导图"},
    {id:"cn-sx-113",subject:"数学",domain:"数与代数 · 问题解决",grade:1,order:13,name:"20以内加减法实际问题",description:"根据总数、部分和相差关系解决求总数、求剩余、求隐藏部分以及比较多少的问题。",evidence:["从情境中找出数量关系","列式并说明答案含义"],source:"一年级代数知识点导图"},
    {id:"cn-sx-114",subject:"数学",domain:"数与代数 · 数的认识",grade:1,order:14,name:"100以内数的认识与数位",description:"用不同方式数到100，理解10个一是十、10个十是一百，认识个位、十位和百位并正确读写数。",evidence:["说出两位数和100的组成","在计数器上正确读写数"],source:"一年级代数知识点导图"},
    {id:"cn-sx-115",subject:"数学",domain:"数与代数 · 数的认识",grade:1,order:15,name:"100以内数的大小比较",description:"先比较位数，再从高位依次比较；也能借助数线判断大小，并描述多一些、少一些、多得多和少得多。",evidence:["正确比较100以内两个数","用合适词语描述数量关系"],source:"一年级代数知识点导图"},
    {id:"cn-sx-116",subject:"数学",domain:"数与代数 · 加减法",grade:1,order:16,name:"整十数加减整十数",description:"把整十数看成几个十，先计算几个十加减几个十，再在结果末尾写0。",evidence:["用小棒或计数器解释算理","正确口算整十数加减"],source:"一年级代数知识点导图"},
    {id:"cn-sx-117",subject:"数学",domain:"数与代数 · 加减法",grade:1,order:17,name:"两位数加一位数和整十数（不进位）",description:"计算两位数加一位数时个位相加，计算两位数加整十数时十位相加，另一数位保持不变。",evidence:["区分两类加法的相同数位","正确计算不进位加法"],source:"一年级代数知识点导图"},
    {id:"cn-sx-118",subject:"数学",domain:"数与代数 · 加减法",grade:1,order:18,name:"两位数减一位数和整十数（不退位）",description:"计算两位数减一位数时个位相减，计算两位数减整十数时十位相减，另一数位保持不变。",evidence:["区分两类减法的相同数位","正确计算不退位减法"],source:"一年级代数知识点导图"},
    {id:"cn-sx-119",subject:"数学",domain:"数与代数 · 问题解决",grade:1,order:19,name:"100以内加减法实际问题",description:"根据图文信息提出并解决求和、求剩余和求相差问题，能说明每一步算式所表示的数量。",evidence:["从图中提取数学信息","独立提出问题并列式解答"],source:"一年级代数知识点导图"},

    {id:"cn-sx-201",subject:"数学",domain:"数与代数 · 加减法",grade:2,order:1,name:"100以内进位加法",description:"用列竖式、凑十法和拆分法计算100以内进位加法，理解相同数位对齐以及满十进一。",evidence:["正确列竖式计算进位加法","用一种口算策略解释结果"],source:"二年级知识点总结"},
    {id:"cn-sx-202",subject:"数学",domain:"数与代数 · 加减法",grade:2,order:2,name:"100以内退位减法",description:"用列竖式、平十法、借十法和拆分法计算100以内退位减法，理解不够减时退一当十。",evidence:["正确列竖式计算退位减法","说明退位后各数位的变化"],source:"二年级知识点总结"},
    {id:"cn-sx-203",subject:"数学",domain:"数与代数 · 加减法",grade:2,order:3,name:"三个数的连加连减",description:"按顺序计算三个数相加或相减；连减时也可先把后两个减数相加，再从第一个数中减去它们的和。",evidence:["正确计算三数连加连减","选择较简便的计算顺序"],source:"二年级知识点总结"},
    {id:"cn-sx-204",subject:"数学",domain:"数与代数 · 大数",grade:2,order:4,name:"生活中的大数与数位",description:"借助计数器和数位顺序表认识个、十、百、千、万，理解相邻数位之间的十进关系并比较大数。",evidence:["正确读写生活中的大数","按数位比较两个大数"],source:"二年级知识点总结"},
    {id:"cn-sx-205",subject:"数学",domain:"数与代数 · 估算",grade:2,order:5,name:"估计物体和文字的数量",description:"用抽样估算法和分段估算估计一页字数、纸张张数等数量，并用实际计数进行验证。",evidence:["选择合适的估算单位或样本","说明估计过程并核对结果"],source:"二年级知识点总结"},
    {id:"cn-sx-206",subject:"数学",domain:"数与代数 · 大数加减",grade:2,order:6,name:"大数加减的竖式与验算",description:"相同数位对齐进行大数加减，处理连续进位和退位，并用加减法互逆关系验算。",evidence:["正确完成大数加减竖式","用逆运算检查结果"],source:"二年级知识点总结"},
    {id:"cn-sx-207",subject:"数学",domain:"数与代数 · 乘法",grade:2,order:7,name:"乘法的意义、符号和读法",description:"理解几个相同加数相加可以用乘法表示，认识乘号、乘数、积并正确读写乘法算式。",evidence:["把相同加数连加改写为乘法","说出乘法算式各部分名称"],source:"二年级知识点总结"},
    {id:"cn-sx-208",subject:"数学",domain:"数与代数 · 乘法",grade:2,order:8,name:"2和5的乘法口诀",description:"理解并熟记2和5的乘法口诀，发现2的口诀依次增加2、5的口诀积的末位是0或5。",evidence:["熟练口算2和5的表内乘法","利用规律补全口诀"],source:"二年级知识点总结"},
    {id:"cn-sx-209",subject:"数学",domain:"数与代数 · 乘法",grade:2,order:9,name:"3和4的乘法口诀",description:"通过相同数量成组的情境理解并熟记3和4的乘法口诀。",evidence:["熟练口算3和4的表内乘法","用乘法解决成组计数问题"],source:"二年级知识点总结"},
    {id:"cn-sx-210",subject:"数学",domain:"数与代数 · 乘法",grade:2,order:10,name:"6至9的乘法口诀",description:"在已有口诀基础上理解并熟记6、7、8、9的乘法口诀，形成完整的表内乘法网络。",evidence:["熟练口算6至9的表内乘法","用已知口诀推导相邻口诀"],source:"二年级知识点总结"},
    {id:"cn-sx-211",subject:"数学",domain:"数与代数 · 除法",grade:2,order:11,name:"平均分与除法的意义",description:"理解把总数平均分成若干份可以用除法表示，认识被除数、除号、除数和商。",evidence:["把平均分情境写成除法算式","说出除法算式各部分名称"],source:"二年级知识点总结"},
    {id:"cn-sx-212",subject:"数学",domain:"数与代数 · 除法",grade:2,order:12,name:"用乘法口诀求商",description:"利用乘除法互逆关系，想除数与哪个数相乘得到被除数，从而求出商。",evidence:["用乘法口诀求表内除法的商","说明乘法与除法之间的联系"],source:"二年级知识点总结"},
    {id:"cn-sx-213",subject:"数学",domain:"数与代数 · 倍",grade:2,order:13,name:"理解倍数关系",description:"理解“A里有几个B，A就是B的几倍”，能用乘法和除法描述与解决倍数关系。",evidence:["用图表示倍数关系","列式解决求几倍的问题"],source:"二年级知识点总结"},
    {id:"cn-sx-214",subject:"数学",domain:"数与代数 · 乘除应用",grade:2,order:14,name:"乘除法实际问题",description:"从情境中辨认相同加数、平均分和倍数关系，明确先求什么、再求什么并列式解答。",evidence:["选择乘法或除法解决问题","解释算式中各数的含义"],source:"二年级知识点总结"},
    {id:"cn-sx-215",subject:"数学",domain:"数与代数 · 有余数除法",grade:2,order:15,name:"有余数除法的初步",description:"理解平均分后可能还有剩余，余数必须小于除数；在实际问题中根据余数决定进一或去尾。",evidence:["写出有余数的除法算式","根据情境正确处理余数"],source:"二年级知识点总结"},

    {id:"cn-sx-301",subject:"数学",domain:"数与代数 · 混合运算",grade:3,order:1,name:"混合运算的顺序",description:"同级运算从左到右；有乘除和加减时先乘除后加减；有括号时先算括号里面。",evidence:["判断混合算式的第一步","按正确顺序完成计算"],source:"三年级数学知识点导图"},
    {id:"cn-sx-302",subject:"数学",domain:"数与代数 · 混合运算",grade:3,order:2,name:"关于0的运算规则",description:"掌握加0、减0、乘0、0除以非0数的结果，并知道0不能作除数。",evidence:["正确判断含0算式的结果","说明为什么0不能作除数"],source:"三年级数学知识点导图"},
    {id:"cn-sx-303",subject:"数学",domain:"数与代数 · 大数加减",grade:3,order:3,name:"三位数连加连减与混合运算",description:"用两个竖式或一个竖式计算三位数连加，灵活计算连减和加减混合，并借助小括号改变顺序。",evidence:["正确计算三位数连加连减","选择合适方法简化计算"],source:"三年级数学知识点导图"},
    {id:"cn-sx-304",subject:"数学",domain:"数与代数 · 大数加减",grade:3,order:4,name:"里程表与大数加减应用",description:"读懂路线图、汽车里程表和电表数据，用较远读数减较近读数或相邻读数作差解决实际问题。",evidence:["解释表中每个读数的含义","列式计算一段路程或本期用量"],source:"三年级数学知识点导图"},
    {id:"cn-sx-305",subject:"数学",domain:"数与代数 · 乘法口算",grade:3,order:5,name:"整十整百数乘一位数",description:"先用0前面的数与一位数相乘，再根据整十或整百在积的末尾添相应个数的0。",evidence:["正确口算整十整百乘一位数","用数的组成解释算法"],source:"三年级数学知识点导图"},
    {id:"cn-sx-306",subject:"数学",domain:"数与代数 · 乘法口算",grade:3,order:6,name:"两位数乘一位数的口算",description:"把两位数分成几十和几，分别乘一位数后再把两个积相加；能处理不进位和进位口算。",evidence:["用拆分法口算两位数乘一位数","说明每个部分积的含义"],source:"三年级数学知识点导图"},
    {id:"cn-sx-307",subject:"数学",domain:"数与代数 · 除法口算",grade:3,order:7,name:"整十整百数除以一位数",description:"把被除数看作几个十或几个百平均分，也可想乘法算除法完成口算。",evidence:["正确口算整十整百除以一位数","用平均分或乘法解释商"],source:"三年级数学知识点导图"},
    {id:"cn-sx-308",subject:"数学",domain:"数与代数 · 除法口算",grade:3,order:8,name:"两位数除以一位数的口算",description:"可想乘法算除法，也可把被除数拆成整十数和一位数，分别除后再把两个商相加。",evidence:["用拆分法口算两位数除以一位数","探索被除数与商的变化"],source:"三年级数学知识点导图"},
    {id:"cn-sx-309",subject:"数学",domain:"数与代数 · 小数",grade:3,order:9,name:"认识、读写生活中的小数",description:"结合商品价格和身高认识小数的整数部分、小数点和小数部分，理解元角分、米分米厘米与小数数位的联系。",evidence:["正确读写一位或两位小数","把价格或长度写成小数"],source:"三年级数学知识点导图"},
    {id:"cn-sx-310",subject:"数学",domain:"数与代数 · 小数",grade:3,order:10,name:"比较小数的大小",description:"先比较整数部分，再依次比较小数点右边各位，直到分出大小。",evidence:["正确比较两个小数","说明逐位比较的过程"],source:"三年级数学知识点导图"},
    {id:"cn-sx-311",subject:"数学",domain:"数与代数 · 小数",grade:3,order:11,name:"小数加减法",description:"小数点对齐即相同数位对齐，从低位算起，处理不进退位以及进位加法、退位减法。",evidence:["正确列竖式计算小数加减","在结果中对齐小数点"],source:"三年级数学知识点导图"},
    {id:"cn-sx-312",subject:"数学",domain:"数与代数 · 整数乘法",grade:3,order:12,name:"两三位数乘一位数的笔算",description:"从个位起依次用一位数乘另一个乘数的每一位，处理不进位、一次进位和连续进位。",evidence:["正确列乘法竖式","处理连续进位并对齐数位"],source:"三年级数学知识点导图"},
    {id:"cn-sx-313",subject:"数学",domain:"数与代数 · 整数乘法",grade:3,order:13,name:"乘数中间或末尾有0的乘法",description:"0也要参与相乘并正确占位；理解0乘任何数得0，任何数加0仍得原数。",evidence:["正确计算含0的多位数乘法","避免漏写占位0"],source:"三年级数学知识点导图"},
    {id:"cn-sx-314",subject:"数学",domain:"数与代数 · 整数乘法",grade:3,order:14,name:"连乘及其应用",description:"连乘按从左到右计算，解决问题时明确先求什么、再求什么。",evidence:["正确计算连乘算式","用连乘解决两步实际问题"],source:"三年级数学知识点导图"},
    {id:"cn-sx-315",subject:"数学",domain:"数与代数 · 整数除法",grade:3,order:15,name:"除法竖式与多位数除以一位数",description:"从被除数最高位除起，除到哪一位商就写在哪一位；余数与下一位合起来继续除，余数必须小于除数。",evidence:["正确书写除法竖式","处理每一步的商与余数"],source:"三年级数学知识点导图"},
    {id:"cn-sx-316",subject:"数学",domain:"数与代数 · 整数除法",grade:3,order:16,name:"商中间或末尾有0",description:"某一位不够商1时在商的对应数位写0占位，区分商是两位数还是三位数。",evidence:["正确确定商的位数","在商中正确写0占位"],source:"三年级数学知识点导图"},
    {id:"cn-sx-317",subject:"数学",domain:"数与代数 · 整数除法",grade:3,order:17,name:"除法验算",description:"没有余数时用商乘除数等于被除数验算；有余数时用商乘除数再加余数。",evidence:["选择正确关系式验算除法","根据验算发现计算错误"],source:"三年级数学知识点导图"},
    {id:"cn-sx-318",subject:"数学",domain:"数与代数 · 整数除法",grade:3,order:18,name:"连除和乘除混合运算",description:"没有括号时从左到右，有括号时先算括号里面，并用乘除混合解决分步问题。",evidence:["按顺序计算连除和乘除混合","用括号表达先算的部分"],source:"三年级数学知识点导图"},
    {id:"cn-sx-319",subject:"数学",domain:"图形与几何 · 认识图形",grade:3,order:19,name:"认识长方形和正方形",description:"认识长方形和正方形的特征，知道长方形对边相等、四个角都是直角；正方形四条边相等、四个角都是直角。",evidence:["辨认长方形和正方形","说出它们的特征"],examples:["课本的封面是长方形","魔方的一个面是正方形","长方形有4条边，对边相等；正方形4条边都相等"],tips:["长方形像拉长的正方形","正方形是特殊的长方形（四条边都相等的长方形）","用三角板的直角去量角，就能判断是不是直角"],commonMistakes:["把长方形和正方形弄混","以为长方形的四条边都相等","忘记正方形的四个角都是直角"],source:"三年级数学知识点导图"},
    {id:"cn-sx-320",subject:"数学",domain:"图形与几何 · 周长",grade:3,order:20,name:"长方形和正方形的周长",description:"理解周长的含义，掌握长方形和正方形周长的计算方法。",evidence:["计算长方形周长","计算正方形周长"],examples:["长方形长5厘米，宽3厘米，周长是(5+3)×2=16厘米","正方形边长4厘米，周长是4×4=16厘米","用绳子绕图形一周，绳子的长度就是周长"],tips:["长方形周长=（长+宽）×2","正方形周长=边长×4","周长就是图形一周的长度"],commonMistakes:["忘记乘2，只算了一条长和一条宽","正方形周长算成边长×2","不知道周长是什么意思"],source:"三年级数学知识点导图"},
    {id:"cn-sx-401",subject:"数学",domain:"数与代数",grade:4,name:"小数的意义与性质",description:"理解小数与十进分数的关系，掌握小数的数位顺序和基本性质。",evidence:["在数位表中表示小数","利用性质化简或改写小数"]},
    {id:"cn-sx-402",subject:"数学",domain:"图形与几何",grade:4,name:"三角形的特性",description:"认识三角形的边、角和高，理解三角形的稳定性以及三边关系。",evidence:["画出三角形指定底边上的高","判断三条线段能否围成三角形"]},
    {id:"cn-sx-403",subject:"数学",domain:"数与代数",grade:4,name:"三位数乘两位数",description:"掌握三位数乘两位数的笔算方法，能正确进行计算。",evidence:["正确进行竖式计算","运用乘法估算解决问题"]},
    {id:"cn-sx-404",subject:"数学",domain:"数与代数",grade:4,name:"除数是两位数的除法",description:"掌握除数是两位数除法的笔算方法，理解商不变的规律。",evidence:["正确进行除法竖式计算","运用商不变规律简便计算"]},
    {id:"cn-sx-405",subject:"数学",domain:"图形与几何",grade:4,name:"平行四边形和梯形",description:"认识平行四边形和梯形的特征，理解它们之间的关系。",evidence:["辨认平行四边形和梯形","画出它们的高"]},
    {id:"cn-sx-406",subject:"数学",domain:"统计与概率",grade:4,name:"平均数",description:"理解平均数的意义，掌握求平均数的方法。",evidence:["计算一组数据的平均数","用平均数解决实际问题"]},
    {id:"cn-sx-501",subject:"数学",domain:"数与代数",grade:5,name:"分数的基本性质",description:"理解分数的分子和分母同时乘或除以相同非零数，分数大小不变。",evidence:["用图形或算式解释基本性质","运用性质约分和通分"]},
    {id:"cn-sx-502",subject:"数学",domain:"图形与几何",grade:5,name:"长方体和正方体的体积",description:"理解体积和体积单位，掌握长方体、正方体体积计算方法。",evidence:["选择合适的体积单位","解决规则物体的体积问题"]},
    {id:"cn-sx-503",subject:"数学",domain:"数与代数",grade:5,name:"分数加减法",description:"掌握同分母分数加减法和异分母分数加减法的计算方法。",evidence:["正确计算同分母分数加减法","正确计算异分母分数加减法"]},
    {id:"cn-sx-504",subject:"数学",domain:"数与代数",grade:5,name:"因数与倍数",description:"理解因数和倍数的概念，掌握找一个数因数和倍数的方法。",evidence:["找出一个数的因数","找出一个数的倍数"]},
    {id:"cn-sx-505",subject:"数学",domain:"图形与几何",grade:5,name:"平行四边形面积",description:"理解平行四边形面积公式的推导过程，掌握面积计算方法。",evidence:["推导平行四边形面积公式","解决平行四边形面积问题"]},
    {id:"cn-sx-506",subject:"数学",domain:"图形与几何",grade:5,name:"三角形面积",description:"理解三角形面积公式的推导过程，掌握面积计算方法。",evidence:["推导三角形面积公式","解决三角形面积问题"]},
    {id:"cn-sx-507",subject:"数学",domain:"统计与概率",grade:5,name:"复式条形统计图",description:"认识复式条形统计图，能根据统计图进行数据分析。",evidence:["绘制复式条形统计图","对比分析两组数据"]},
    {id:"cn-sx-601",subject:"数学",domain:"数与代数",grade:6,name:"比和比例",description:"理解比的意义和基本性质，认识成比例的量并解决比例问题。",evidence:["正确求比值和化简比","判断两种量是否成比例"]},
    {id:"cn-sx-602",subject:"数学",domain:"综合实践",grade:6,name:"百分数解决问题",description:"理解百分数表示两个量之间的倍比关系，解决折扣、增长率等实际问题。",evidence:["在情境中确定单位“1”","列式解决常见百分数问题"]},
    {id:"cn-sx-603",subject:"数学",domain:"数与代数",grade:6,name:"分数乘法",description:"理解分数乘法的意义，掌握分数乘整数和分数乘分数的计算方法。",evidence:["正确计算分数乘法","解决分数乘法实际问题"]},
    {id:"cn-sx-604",subject:"数学",domain:"数与代数",grade:6,name:"分数除法",description:"理解分数除法的意义，掌握分数除法的计算方法。",evidence:["正确计算分数除法","解决分数除法实际问题"]},
    {id:"cn-sx-605",subject:"数学",domain:"图形与几何",grade:6,name:"圆的周长与面积",description:"理解圆周率的意义，掌握圆的周长和面积计算公式。",evidence:["计算圆的周长","计算圆的面积"]},
    {id:"cn-sx-606",subject:"数学",domain:"图形与几何",grade:6,name:"圆柱与圆锥",description:"认识圆柱和圆锥的特征，掌握圆柱表面积和体积的计算方法。",evidence:["计算圆柱的表面积","计算圆柱和圆锥的体积"]},
    {id:"cn-sx-607",subject:"数学",domain:"统计与概率",grade:6,name:"扇形统计图",description:"认识扇形统计图，能根据统计图分析各部分与整体的关系。",evidence:["读懂扇形统计图","根据数据绘制扇形统计图"]},

    {id:"cn-yy-101",subject:"英语",domain:"听说",grade:1,name:"课堂常用问候",description:"听懂并使用Hello、Good morning、Goodbye等简单问候语。",evidence:["在合适情境使用问候语","能回应他人的简单问候"]},
    {id:"cn-yy-201",subject:"英语",domain:"词汇与语法",grade:2,name:"表达颜色与数量",description:"听说认读常见颜色和1至20的数字，并在简单句型中使用。",evidence:["说出常见颜色词","用数字描述物品数量"]},
    {id:"cn-yy-301",subject:"英语",domain:"表达",grade:3,name:"简单介绍自己",description:"使用姓名、年龄、爱好等基础信息进行简短的自我介绍。",evidence:["连续说出三项个人信息","语音基本清楚并能被理解"]},
    {id:"cn-yy-401",subject:"英语",domain:"词汇与语法",grade:4,name:"一般现在时表达日常活动",description:"使用一般现在时描述自己或他人的日常活动和习惯。",evidence:["正确使用常见动词表达日常活动","初步注意第三人称单数形式"]},
    {id:"cn-yy-501",subject:"英语",domain:"阅读",grade:5,name:"提取短文关键信息",description:"阅读简短语篇，定位人物、时间、地点、事件等关键信息。",evidence:["根据问题定位文本信息","用关键词概括短文内容"]},
    {id:"cn-yy-601",subject:"英语",domain:"表达",grade:6,name:"围绕主题进行简短表达",description:"围绕熟悉主题组织若干有联系的句子，进行口头或书面表达。",evidence:["内容围绕同一主题","使用连接词让句子形成联系"]},

    {id:"cn-kx-101",subject:"科学",domain:"生命科学",grade:1,name:"观察植物的特征",description:"运用眼、鼻、手等感官安全地观察植物的颜色、形状和结构。",evidence:["从两个以上方面描述植物","用图画或词语记录观察结果"]},
    {id:"cn-kx-201",subject:"科学",domain:"物质科学",grade:2,name:"比较材料的性质",description:"通过观察和简单实验比较木材、金属、塑料等材料的软硬、轻重等性质。",evidence:["选择合适方法比较材料","根据性质解释材料用途"]},
    {id:"cn-kx-301",subject:"科学",domain:"地球与宇宙",grade:3,name:"天气与气温观测",description:"使用温度计测量气温，连续记录天气并发现变化规律。",evidence:["正确读取气温数据","使用表格记录连续天气"]},
    {id:"cn-kx-401",subject:"科学",domain:"物质科学",grade:4,name:"声音由振动产生",description:"通过实验观察物体发声时的振动，理解声音由物体振动产生。",evidence:["举例说明发声物体在振动","设计简单实验验证观点"]},
    {id:"cn-kx-402",subject:"科学",domain:"技术与工程",grade:4,name:"设计与制作简单电路",description:"认识电池、导线和小灯泡，连接能够使小灯泡发光的简单电路。",evidence:["正确连接闭合电路","排查小灯泡不亮的常见原因"]},
    {id:"cn-kx-501",subject:"科学",domain:"生命科学",grade:5,name:"食物链与食物网",description:"理解生物之间吃与被吃的关系，用食物链和食物网表示能量联系。",evidence:["正确书写简单食物链","解释一种生物变化对其他生物的影响"]},
    {id:"cn-kx-502",subject:"科学",domain:"地球与宇宙",grade:5,name:"地球的自转与昼夜",description:"借助模型理解地球自转的方向，并解释昼夜交替现象。",evidence:["用模型演示昼夜交替","说明同一时刻不同地区昼夜可能不同"]},
    {id:"cn-kx-601",subject:"科学",domain:"地球与宇宙",grade:6,name:"太阳系中的地球",description:"认识太阳系的基本组成，理解地球在太阳系中的位置和适宜生命的条件。",evidence:["说出太阳系主要天体类型","解释地球适宜生命的部分条件"]},
    {id:"cn-kx-602",subject:"科学",domain:"技术与工程",grade:6,name:"工程设计的迭代",description:"明确需求与限制，提出方案、制作模型、测试并根据证据改进设计。",evidence:["根据需求提出多个方案","使用测试结果解释改进决定"]}
  ],
  dependencies: [
    ["cn-yw-103","cn-yw-102"],["cn-yw-201","cn-yw-101"],["cn-yw-202","cn-yw-103"],["cn-yw-301","cn-yw-103"],["cn-yw-302","cn-yw-103"],["cn-yw-401","cn-yw-301"],["cn-yw-402","cn-yw-202"],["cn-yw-501","cn-yw-401"],["cn-yw-502","cn-yw-402"],["cn-yw-601","cn-yw-401"],["cn-yw-601","cn-yw-501"],
    ["cn-sx-102","cn-sx-101"],["cn-sx-103","cn-sx-102"],["cn-sx-104","cn-sx-103"],["cn-sx-105","cn-sx-104"],["cn-sx-106","cn-sx-105"],["cn-sx-107","cn-sx-106"],["cn-sx-108","cn-sx-104"],
    ["cn-sx-109","cn-sx-102"],["cn-sx-109","cn-sx-103"],["cn-sx-110","cn-sx-109"],["cn-sx-110","cn-sx-106"],["cn-sx-111","cn-sx-106"],["cn-sx-111","cn-sx-109"],["cn-sx-112","cn-sx-106"],["cn-sx-112","cn-sx-109"],["cn-sx-113","cn-sx-111"],["cn-sx-113","cn-sx-112"],["cn-sx-113","cn-sx-108"],
    ["cn-sx-114","cn-sx-109"],["cn-sx-115","cn-sx-114"],["cn-sx-116","cn-sx-114"],["cn-sx-117","cn-sx-116"],["cn-sx-117","cn-sx-110"],["cn-sx-118","cn-sx-116"],["cn-sx-118","cn-sx-112"],["cn-sx-119","cn-sx-117"],["cn-sx-119","cn-sx-118"],["cn-sx-119","cn-sx-113"],

    ["cn-sx-201","cn-sx-117"],["cn-sx-202","cn-sx-118"],["cn-sx-203","cn-sx-201"],["cn-sx-203","cn-sx-202"],["cn-sx-204","cn-sx-114"],["cn-sx-205","cn-sx-204"],["cn-sx-206","cn-sx-203"],["cn-sx-206","cn-sx-204"],
    ["cn-sx-207","cn-sx-106"],["cn-sx-208","cn-sx-207"],["cn-sx-209","cn-sx-208"],["cn-sx-210","cn-sx-209"],["cn-sx-211","cn-sx-207"],["cn-sx-212","cn-sx-210"],["cn-sx-212","cn-sx-211"],["cn-sx-213","cn-sx-207"],["cn-sx-214","cn-sx-212"],["cn-sx-214","cn-sx-213"],["cn-sx-215","cn-sx-212"],

    ["cn-sx-301","cn-sx-107"],["cn-sx-301","cn-sx-214"],["cn-sx-302","cn-sx-105"],["cn-sx-302","cn-sx-211"],["cn-sx-303","cn-sx-206"],["cn-sx-303","cn-sx-301"],["cn-sx-304","cn-sx-303"],
    ["cn-sx-305","cn-sx-210"],["cn-sx-306","cn-sx-305"],["cn-sx-307","cn-sx-212"],["cn-sx-308","cn-sx-307"],["cn-sx-309","cn-sx-204"],["cn-sx-310","cn-sx-309"],["cn-sx-311","cn-sx-310"],["cn-sx-311","cn-sx-201"],["cn-sx-311","cn-sx-202"],
    ["cn-sx-312","cn-sx-306"],["cn-sx-313","cn-sx-312"],["cn-sx-313","cn-sx-302"],["cn-sx-314","cn-sx-312"],["cn-sx-314","cn-sx-301"],["cn-sx-315","cn-sx-308"],["cn-sx-315","cn-sx-215"],["cn-sx-316","cn-sx-315"],["cn-sx-316","cn-sx-302"],["cn-sx-317","cn-sx-315"],["cn-sx-318","cn-sx-315"],["cn-sx-318","cn-sx-301"],
    ["cn-sx-319","cn-sx-103"],["cn-sx-320","cn-sx-319"],

    ["cn-sx-401","cn-sx-309"],["cn-sx-402","cn-sx-319"],["cn-sx-403","cn-sx-312"],["cn-sx-404","cn-sx-315"],["cn-sx-405","cn-sx-402"],["cn-sx-406","cn-sx-304"],
    ["cn-sx-501","cn-sx-309"],["cn-sx-502","cn-sx-402"],["cn-sx-503","cn-sx-501"],["cn-sx-504","cn-sx-210"],["cn-sx-505","cn-sx-405"],["cn-sx-506","cn-sx-505"],["cn-sx-507","cn-sx-406"],
    ["cn-sx-601","cn-sx-501"],["cn-sx-602","cn-sx-601"],["cn-sx-603","cn-sx-501"],["cn-sx-604","cn-sx-603"],["cn-sx-605","cn-sx-302"],["cn-sx-606","cn-sx-502"],["cn-sx-607","cn-sx-507"],
    ["cn-yy-201","cn-yy-101"],["cn-yy-301","cn-yy-201"],["cn-yy-401","cn-yy-301"],["cn-yy-501","cn-yy-401"],["cn-yy-601","cn-yy-501"],
    ["cn-kx-201","cn-kx-101"],["cn-kx-301","cn-kx-101"],["cn-kx-401","cn-kx-201"],["cn-kx-402","cn-kx-201"],["cn-kx-501","cn-kx-101"],["cn-kx-502","cn-kx-301"],["cn-kx-601","cn-kx-502"],["cn-kx-602","cn-kx-402"],
    ["cn-kx-301","cn-sx-101","recommended"],["cn-yw-302","cn-yw-102","recommended"]
  ].map(([topicId, prerequisiteId, type = "required"]) => ({topicId, prerequisiteId, type}))
};
